program Office4DDemo;

{$APPTYPE CONSOLE}

uses
  System.SysUtils,
  System.IOUtils,
  System.Classes,
  Office4D.Word,
  Office4D.Excel;

procedure CreateWordDocument(const FileName: string);
var
  Doc: IWordDocument;
  Para: IWordParagraph;
  Run: IWordRun;
  Table: IWordTable;
begin
  WriteLn('Creating Word document: ', FileName);

  Doc := TWordDocumentFactory.CreateDocument;

  // Set page settings
  Doc.PageOrientation := TPageOrientation.Portrait;
  Doc.PageMargins := TPageMargins.Create(1440, 1440, 1440, 1440); // 1 inch margins

  // Set header and footer
  Doc.Header.Text := 'Office4D Demo Document';
  Doc.Footer.Text := 'Page 1 - Generated by Office4D';

  // Title paragraph with formatting
  Para := Doc.AddParagraph;
  Run := Para.AddRun('Office4D Demo Document');
  Run.Bold := True;

  // Empty line
  Doc.AddParagraph;

  // Introduction paragraph with hyperlink
  Para := Doc.AddParagraph;
  Para.AddRun('This document was created with ');
  Run := Para.AddRun('Office4D');
  Run.Bold := True;
  Run.Italic := True;
  Para.AddRun(' - a pure Delphi library for Office Open XML. Visit our website at ');
  Run := Para.AddRun('GitHub Repository');
  Run.Hyperlink := 'https://github.com/example/office4d';
  Run.Underline := True;
  Para.AddRun(' for more information.');

  // Empty line
  Doc.AddParagraph;

  // Features heading
  Para := Doc.AddParagraph;
  Run := Para.AddRun('Features demonstrated in this document:');
  Run.Bold := True;

  // Bullet list
  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Bullet;
  Run := Para.AddRun('Text formatting (bold, italic, underline)');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Bullet;
  Para.AddRun('Hyperlinks with clickable URLs');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Bullet;
  Para.AddRun('Bullet and numbered lists');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Bullet;
  Para.AddRun('Tables with data');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Bullet;
  Para.AddRun('Page settings (margins, orientation)');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Bullet;
  Para.AddRun('Headers and footers');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Bullet;
  Para.AddRun('Line spacing and indentation');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Bullet;
  Para.AddRun('Table styling (borders, shading, column widths)');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Bullet;
  Para.AddRun('Embedded images');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Bullet;
  Para.AddRun('Page breaks');

  // Empty line
  Doc.AddParagraph;

  // Numbered list section
  Para := Doc.AddParagraph;
  Run := Para.AddRun('Steps to use Office4D:');
  Run.Bold := True;

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Numbered;
  Para.AddRun('Add Office4D units to your project');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Numbered;
  Para.AddRun('Create a document using the factory');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Numbered;
  Para.AddRun('Add content (paragraphs, tables, etc.)');

  Para := Doc.AddParagraph;
  Para.ListStyle := TListStyle.Numbered;
  Para.AddRun('Save to file or stream');

  // Empty line before table
  Doc.AddParagraph;

  // Table section
  Para := Doc.AddParagraph;
  Run := Para.AddRun('Sample Data Table:');
  Run.Bold := True;

  Table := Doc.AddTable(4, 3);

  // Header row
  Table.Cells[0, 0].Text := 'Product';
  Table.Cells[0, 1].Text := 'Quantity';
  Table.Cells[0, 2].Text := 'Price';

  // Data rows
  Table.Cells[1, 0].Text := 'Laptop';
  Table.Cells[1, 1].Text := '5';
  Table.Cells[1, 2].Text := '$999.00';

  Table.Cells[2, 0].Text := 'Mouse';
  Table.Cells[2, 1].Text := '25';
  Table.Cells[2, 2].Text := '$29.95';

  Table.Cells[3, 0].Text := 'Keyboard';
  Table.Cells[3, 1].Text := '15';
  Table.Cells[3, 2].Text := '$79.50';

  // Empty line
  Doc.AddParagraph;

  // Line Spacing Section
  Para := Doc.AddParagraph;
  Run := Para.AddRun('Line Spacing Demo:');
  Run.Bold := True;

  Para := Doc.AddParagraph;
  Para.LineSpacing := TLineSpacing.Double;
  Para.AddRun('This paragraph uses double line spacing. Notice the extra space between lines when there is more text that wraps to multiple lines in the document.');

  Para := Doc.AddParagraph;
  Para.LineSpacing := TLineSpacing.Create(240, TLineSpacingRule.Auto, 200, 200);
  Para.AddRun('This paragraph has space before and after (200 twips each).');

  // Empty line
  Doc.AddParagraph;

  // Indentation Section
  Para := Doc.AddParagraph;
  Run := Para.AddRun('Indentation Demo:');
  Run.Bold := True;

  Para := Doc.AddParagraph;
  Para.Indent := TParagraphIndent.Create(720, 0, 0);
  Para.AddRun('This paragraph is indented 0.5 inch from the left margin.');

  Para := Doc.AddParagraph;
  Para.Indent := TParagraphIndent.Create(0, 0, 720);
  Para.AddRun('This paragraph has a first-line indent of 0.5 inch, which is commonly used for the beginning of new paragraphs in formal documents.');

  // Page Break
  Para := Doc.AddParagraph;
  Para.AddPageBreak;

  // Styled Table Section (new page)
  Para := Doc.AddParagraph;
  Run := Para.AddRun('Styled Table Demo:');
  Run.Bold := True;

  Doc.AddParagraph;

  Table := Doc.AddTable(4, 3);
  Table.Borders := TTableBorders.All(TTableBorder.Create(TBorderStyle.Single, 8, '000000'));
  Table.SetColumnWidths([3000, 2000, 2000]);

  // Header row with shading
  Table.Cells[0, 0].Text := 'Feature';
  Table.Cells[0, 0].Shading := '4472C4';
  Table.Cells[0, 1].Text := 'Status';
  Table.Cells[0, 1].Shading := '4472C4';
  Table.Cells[0, 2].Text := 'Version';
  Table.Cells[0, 2].Shading := '4472C4';

  // Data rows
  Table.Cells[1, 0].Text := 'Page Breaks';
  Table.Cells[1, 1].Text := 'Complete';
  Table.Cells[1, 1].Shading := '70AD47';
  Table.Cells[1, 2].Text := 'v3.0';

  Table.Cells[2, 0].Text := 'Line Spacing';
  Table.Cells[2, 1].Text := 'Complete';
  Table.Cells[2, 1].Shading := '70AD47';
  Table.Cells[2, 2].Text := 'v3.0';

  Table.Cells[3, 0].Text := 'Images';
  Table.Cells[3, 1].Text := 'Complete';
  Table.Cells[3, 1].Shading := '70AD47';
  Table.Cells[3, 2].Text := 'v3.0';

  // Empty line
  Doc.AddParagraph;

  // Image Section
  Para := Doc.AddParagraph;
  Run := Para.AddRun('Embedded Image Demo:');
  Run.Bold := True;

  Doc.AddParagraph;

  Para := Doc.AddParagraph;
  Para.AddRun('Below is an embedded 1x1 pixel PNG image (scaled to 50x50):');

  Para := Doc.AddParagraph;
  Para.Alignment := TParagraphAlignment.Center;
  Run := Para.AddRun('');
  // Minimal 1x1 red pixel PNG
  var PngData: TBytes := [$89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D,
    $49, $48, $44, $52, $00, $00, $00, $01, $00, $00, $00, $01, $08, $02, $00, $00,
    $00, $90, $77, $53, $DE, $00, $00, $00, $0C, $49, $44, $41, $54, $08, $D7, $63,
    $F8, $CF, $C0, $00, $00, $00, $03, $00, $01, $00, $18, $DD, $8D, $B4, $00, $00,
    $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82];
  Run.AddImage(PngData, 'png', 50, 50);

  // Footer
  Doc.AddParagraph;
  Para := Doc.AddParagraph;
  Para.AddRun('Generated on: ');
  Run := Para.AddRun(FormatDateTime('yyyy-mm-dd hh:nn:ss', Now));
  Run.Italic := True;

  Doc.SaveToFile(FileName);
  WriteLn('Word document created successfully!');
  WriteLn;
end;

procedure CreateExcelWorkbook(const FileName: string);
var
  Workbook: IExcelWorkbook;
  Sheet: IExcelSheet;
begin
  WriteLn('Creating Excel workbook: ', FileName);

  Workbook := TExcelWorkbookFactory.Create;

  // Sheet 1: Product data with styling
  Sheet := Workbook.AddSheet('Products');

  // Set column widths
  Sheet.SetColumnWidth('A', 15);
  Sheet.SetColumnWidth('B', 12);
  Sheet.SetColumnWidth('C', 12);
  Sheet.SetColumnWidth('D', 12);
  Sheet.SetColumnWidth('E', 10);
  Sheet.SetColumnWidth('F', 18);

  // Headers with bold and background color
  Sheet.Cell['A1'].AsString := 'Product';
  Sheet.Cell['A1'].Bold := True;
  Sheet.Cell['A1'].BackgroundColor := $4472C4; // Blue

  Sheet.Cell['B1'].AsString := 'Quantity';
  Sheet.Cell['B1'].Bold := True;
  Sheet.Cell['B1'].BackgroundColor := $4472C4;

  Sheet.Cell['C1'].AsString := 'Unit Price';
  Sheet.Cell['C1'].Bold := True;
  Sheet.Cell['C1'].BackgroundColor := $4472C4;

  Sheet.Cell['D1'].AsString := 'Total';
  Sheet.Cell['D1'].Bold := True;
  Sheet.Cell['D1'].BackgroundColor := $4472C4;

  Sheet.Cell['E1'].AsString := 'In Stock';
  Sheet.Cell['E1'].Bold := True;
  Sheet.Cell['E1'].BackgroundColor := $4472C4;

  Sheet.Cell['F1'].AsString := 'Last Updated';
  Sheet.Cell['F1'].Bold := True;
  Sheet.Cell['F1'].BackgroundColor := $4472C4;

  // Row 2 - Laptop
  Sheet.Cell['A2'].AsString := 'Laptop';
  Sheet.Cell['B2'].AsFloat := 5;
  Sheet.Cell['C2'].AsFloat := 999.00;
  Sheet.Cell['C2'].NumberFormat := '"$"#,##0.00';
  Sheet.Cell['D2'].SetFormula('B2*C2', 5 * 999.00);
  Sheet.Cell['D2'].NumberFormat := '"$"#,##0.00';
  Sheet.Cell['E2'].AsBoolean := True;
  Sheet.Cell['F2'].AsDateTime := Now;

  // Row 3 - Mouse
  Sheet.Cell['A3'].AsString := 'Mouse';
  Sheet.Cell['B3'].AsFloat := 25;
  Sheet.Cell['C3'].AsFloat := 29.95;
  Sheet.Cell['C3'].NumberFormat := '"$"#,##0.00';
  Sheet.Cell['D3'].SetFormula('B3*C3', 25 * 29.95);
  Sheet.Cell['D3'].NumberFormat := '"$"#,##0.00';
  Sheet.Cell['E3'].AsBoolean := True;
  Sheet.Cell['F3'].AsDateTime := Now - 1;

  // Row 4 - Monitor
  Sheet.Cell['A4'].AsString := 'Monitor';
  Sheet.Cell['B4'].AsFloat := 0;
  Sheet.Cell['C4'].AsFloat := 399.00;
  Sheet.Cell['C4'].NumberFormat := '"$"#,##0.00';
  Sheet.Cell['D4'].SetFormula('B4*C4', 0);
  Sheet.Cell['D4'].NumberFormat := '"$"#,##0.00';
  Sheet.Cell['E4'].AsBoolean := False;
  Sheet.Cell['E4'].BackgroundColor := $FF0000; // Red for out of stock
  Sheet.Cell['F4'].AsDateTime := Now - 7;

  // Row 5 - Keyboard
  Sheet.Cell['A5'].AsString := 'Keyboard';
  Sheet.Cell['B5'].AsFloat := 15;
  Sheet.Cell['C5'].AsFloat := 79.50;
  Sheet.Cell['C5'].NumberFormat := '"$"#,##0.00';
  Sheet.Cell['D5'].SetFormula('B5*C5', 15 * 79.50);
  Sheet.Cell['D5'].NumberFormat := '"$"#,##0.00';
  Sheet.Cell['E5'].AsBoolean := True;
  Sheet.Cell['F5'].AsDateTime := Now - 2;

  // Summary row with formulas
  Sheet.Cell['A7'].AsString := 'Total:';
  Sheet.Cell['A7'].Bold := True;
  Sheet.Cell['B7'].SetFormula('SUM(B2:B5)', 5 + 25 + 0 + 15);
  Sheet.Cell['B7'].Bold := True;
  Sheet.Cell['D7'].SetFormula('SUM(D2:D5)', 5*999 + 25*29.95 + 0 + 15*79.50);
  Sheet.Cell['D7'].Bold := True;
  Sheet.Cell['D7'].NumberFormat := '"$"#,##0.00';
  Sheet.Cell['D7'].BackgroundColor := $70AD47; // Green for total

  // Sheet 2: Percentages Demo
  Sheet := Workbook.AddSheet('Percentages');
  Sheet.Cell['A1'].AsString := 'Discount Rates';
  Sheet.Cell['A1'].Bold := True;

  Sheet.Cell['A3'].AsString := 'Standard';
  Sheet.Cell['B3'].AsFloat := 0.05;
  Sheet.Cell['B3'].NumberFormat := '0%';

  Sheet.Cell['A4'].AsString := 'Premium';
  Sheet.Cell['B4'].AsFloat := 0.10;
  Sheet.Cell['B4'].NumberFormat := '0%';

  Sheet.Cell['A5'].AsString := 'VIP';
  Sheet.Cell['B5'].AsFloat := 0.15;
  Sheet.Cell['B5'].NumberFormat := '0%';

  // Sheet 3: Merged Cells Demo
  Sheet := Workbook.AddSheet('Merged Cells');

  // Title spanning multiple columns
  Sheet.MergeCells('A1:D1');
  Sheet.Cell['A1'].AsString := 'Quarterly Sales Report';
  Sheet.Cell['A1'].Bold := True;
  Sheet.Cell['A1'].BackgroundColor := $4472C4;

  // Headers
  Sheet.Cell['A3'].AsString := 'Region';
  Sheet.Cell['A3'].Bold := True;
  Sheet.Cell['B3'].AsString := 'Q1';
  Sheet.Cell['B3'].HAlign := TExcelHAlign.Center;
  Sheet.Cell['B3'].Bold := True;
  Sheet.Cell['C3'].AsString := 'Q2';
  Sheet.Cell['C3'].HAlign := TExcelHAlign.Center;
  Sheet.Cell['C3'].Bold := True;
  Sheet.Cell['D3'].AsString := 'Total';
  Sheet.Cell['D3'].HAlign := TExcelHAlign.Center;
  Sheet.Cell['D3'].Bold := True;

  // Data
  Sheet.Cell['A4'].AsString := 'North';
  Sheet.Cell['B4'].AsFloat := 15000;
  Sheet.Cell['C4'].AsFloat := 18000;
  Sheet.Cell['D4'].SetFormula('B4+C4', 33000);

  Sheet.Cell['A5'].AsString := 'South';
  Sheet.Cell['B5'].AsFloat := 12000;
  Sheet.Cell['C5'].AsFloat := 14500;
  Sheet.Cell['D5'].SetFormula('B5+C5', 26500);

  // Merged footer
  Sheet.MergeCells('A7:C7');
  Sheet.Cell['A7'].AsString := 'Grand Total:';
  Sheet.Cell['A7'].Bold := True;
  Sheet.Cell['D7'].SetFormula('D4+D5', 59500);
  Sheet.Cell['D7'].Bold := True;
  Sheet.Cell['D7'].BackgroundColor := $70AD47;

  // Sheet 4: Info
  Sheet := Workbook.AddSheet('Info');
  Sheet.SetColumnWidth('A', 50);

  Sheet.Cell['A1'].AsString := 'Office4D Demo';
  Sheet.Cell['A1'].Bold := True;

  Sheet.Cell['A3'].AsString := 'Features demonstrated:';
  Sheet.Cell['A4'].AsString := '- Cell data types (string, number, boolean, date)';
  Sheet.Cell['A5'].AsString := '- Cell formatting (bold, background color)';
  Sheet.Cell['A6'].AsString := '- Number formats (currency, percentage)';
  Sheet.Cell['A7'].AsString := '- Formulas with calculated values';
  Sheet.Cell['A8'].AsString := '- Multiple worksheets';
  Sheet.Cell['A9'].AsString := '- Column widths';
  Sheet.Cell['A10'].AsString := '- Merged cells';

  Sheet.Cell['A12'].AsString := 'Generated:';
  Sheet.Cell['B12'].AsDateTime := Now;

  Workbook.SaveToFile(FileName);
  WriteLn('Excel workbook created successfully!');
  WriteLn;
end;

var
  DesktopPath: string;
  WordFile, ExcelFile: string;
begin
  try
    DesktopPath := TPath.Combine(TPath.Combine(GetEnvironmentVariable('USERPROFILE'), 'Desktop'), '');

    WordFile := TPath.Combine(DesktopPath, 'Office4D_Demo.docx');
    ExcelFile := TPath.Combine(DesktopPath, 'Office4D_Demo.xlsx');

    WriteLn('===========================================');
    WriteLn('       Office4D Demonstration');
    WriteLn('===========================================');
    WriteLn;
    WriteLn('This demo showcases all Office4D features:');
    WriteLn;
    WriteLn('Word (.docx):');
    WriteLn('  - Text formatting (bold, italic, underline)');
    WriteLn('  - Hyperlinks');
    WriteLn('  - Bullet and numbered lists');
    WriteLn('  - Tables with borders, shading, and column widths');
    WriteLn('  - Page settings (margins, orientation)');
    WriteLn('  - Headers and footers');
    WriteLn('  - Line spacing (single, double, custom)');
    WriteLn('  - Paragraph indentation');
    WriteLn('  - Page breaks');
    WriteLn('  - Embedded images');
    WriteLn;
    WriteLn('Excel (.xlsx):');
    WriteLn('  - Cell data types (string, number, boolean, date)');
    WriteLn('  - Cell formatting (bold, background color)');
    WriteLn('  - Number formats (currency, percentage)');
    WriteLn('  - Formulas');
    WriteLn('  - Multiple worksheets');
    WriteLn('  - Column widths');
    WriteLn('  - Merged cells');
    WriteLn;
    WriteLn('===========================================');
    WriteLn;

    CreateWordDocument(WordFile);
    CreateExcelWorkbook(ExcelFile);

    WriteLn('===========================================');
    WriteLn('Files created on your Desktop:');
    WriteLn('  - Office4D_Demo.docx');
    WriteLn('  - Office4D_Demo.xlsx');
    WriteLn('===========================================');
    WriteLn;
    WriteLn('Press Enter to exit...');
    ReadLn;
  except
    on E: Exception do
    begin
      WriteLn('Error: ', E.Message);
      ReadLn;
    end;
  end;
end.
